//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitGoals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int GoalID { get; set; }
        public string GoalName { get; set; }
        public int GoalTypeID { get; set; }
        public int GoalQuantity { get; set; }
        public int MeasurementID { get; set; }
        public System.DateTime GoalDeadline { get; set; }
        public string UserAssociation { get; set; }
    
        public virtual GoalType GoalType { get; set; }
        public virtual Measurement Measurement { get; set; }
    }
}
